import type {
  Category,
  Product,
  Tag,
  User,
  Order,
  OrderItem,
  Coupon,
  SupportTicket,
  SupportReply,
  Review,
  DashboardStats,
  BlogPost,
  StaticPage,
  FAQ,
  Download,
  Cart,
} from '../../shared-types/src/index';

// ─────────────────────────────────────────────
// Categories
// ─────────────────────────────────────────────

export const mockCategories: Category[] = [
  {
    id: 'cat-01',
    name: 'Microservices Implementation',
    slug: 'microservices-implementation',
    description: 'Production-ready microservice packages for scalable architectures.',
    sortOrder: 1,
    productCount: 3,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-02',
    name: 'SaaS Solutions',
    slug: 'saas-solutions',
    description: 'Full-featured SaaS starter kits and complete application templates.',
    sortOrder: 2,
    productCount: 3,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-03',
    name: 'Website Templates',
    slug: 'website-templates',
    description: 'Modern, responsive website templates built with cutting-edge tech.',
    sortOrder: 3,
    productCount: 2,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-04',
    name: 'Dashboard Templates',
    slug: 'dashboard-templates',
    description: 'Admin and analytics dashboard templates with charts and data tables.',
    sortOrder: 4,
    productCount: 2,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-05',
    name: 'UI/UX Templates',
    slug: 'ui-ux-templates',
    description: 'Component libraries and UI kits for rapid interface development.',
    sortOrder: 5,
    productCount: 1,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-06',
    name: 'Figma Kits',
    slug: 'figma-kits',
    description: 'Professional Figma design files, UI kits, and design systems.',
    sortOrder: 6,
    productCount: 2,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-07',
    name: 'Photoshop Assets',
    slug: 'photoshop-assets',
    description: 'High-quality PSD templates, mockups, and design assets.',
    sortOrder: 7,
    productCount: 2,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-08',
    name: 'Design Systems',
    slug: 'design-systems',
    description: 'Comprehensive design systems with tokens, components, and guidelines.',
    sortOrder: 8,
    productCount: 1,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-09',
    name: 'API Packages',
    slug: 'api-packages',
    description: 'REST and GraphQL API starter packages with authentication and docs.',
    sortOrder: 9,
    productCount: 1,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-10',
    name: 'Source Code Packages',
    slug: 'source-code-packages',
    description: 'Reusable modules and packages for popular frameworks.',
    sortOrder: 10,
    productCount: 1,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-11',
    name: 'Documentation & Guides',
    slug: 'documentation-guides',
    description: 'Developer documentation templates and technical writing guides.',
    sortOrder: 11,
    productCount: 1,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Tags
// ─────────────────────────────────────────────

export const mockTags: Tag[] = [
  { id: 'tag-01', name: 'Node.js', slug: 'nodejs' },
  { id: 'tag-02', name: 'TypeScript', slug: 'typescript' },
  { id: 'tag-03', name: 'Docker', slug: 'docker' },
  { id: 'tag-04', name: 'Kubernetes', slug: 'kubernetes' },
  { id: 'tag-05', name: 'React', slug: 'react' },
  { id: 'tag-06', name: 'Next.js', slug: 'nextjs' },
  { id: 'tag-07', name: 'Tailwind CSS', slug: 'tailwindcss' },
  { id: 'tag-08', name: 'Figma', slug: 'figma' },
  { id: 'tag-09', name: 'Photoshop', slug: 'photoshop' },
  { id: 'tag-10', name: 'REST API', slug: 'rest-api' },
  { id: 'tag-11', name: 'Laravel', slug: 'laravel' },
  { id: 'tag-12', name: 'PHP', slug: 'php' },
  { id: 'tag-13', name: 'Stripe', slug: 'stripe' },
  { id: 'tag-14', name: 'JWT', slug: 'jwt' },
  { id: 'tag-15', name: 'PostgreSQL', slug: 'postgresql' },
  { id: 'tag-16', name: 'Redis', slug: 'redis' },
  { id: 'tag-17', name: 'Microservices', slug: 'microservices' },
  { id: 'tag-18', name: 'SaaS', slug: 'saas' },
  { id: 'tag-19', name: 'Dashboard', slug: 'dashboard' },
  { id: 'tag-20', name: 'Documentation', slug: 'documentation' },
];

// ─────────────────────────────────────────────
// Products
// ─────────────────────────────────────────────

export const mockProducts: Product[] = [
  {
    id: 'prod-01',
    title: 'Auth Microservice API Kit',
    slug: 'auth-microservice-api-kit',
    categoryId: 'cat-01',
    shortDescription: 'Production-ready authentication microservice with JWT, OAuth2, and 2FA support.',
    description: `A fully production-ready authentication microservice built with Node.js and TypeScript. Includes JWT access/refresh tokens, OAuth2 social login (Google, GitHub), two-factor authentication, role-based access control, rate limiting, and a complete REST API. Comes with Docker and Kubernetes deployment configurations, along with OpenAPI docs and 95%+ test coverage.`,
    price: 129,
    currency: 'USD',
    previewImages: [
      { id: 'pi-01-1', productId: 'prod-01', url: '/placeholders/product-01-a.svg', altText: 'Auth service architecture diagram', sortOrder: 1 },
      { id: 'pi-01-2', productId: 'prod-01', url: '/placeholders/product-01-b.svg', altText: 'API endpoint documentation', sortOrder: 2 },
      { id: 'pi-01-3', productId: 'prod-01', url: '/placeholders/product-01-c.svg', altText: 'Dashboard screenshot', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/auth-kit',
    tags: [mockTags[0], mockTags[1], mockTags[2], mockTags[13], mockTags[16]],
    technologies: ['Node.js', 'TypeScript', 'Express', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
    version: '2.4.1',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.8,
    reviewCount: 47,
    salesCount: 312,
    downloadLimit: 5,
    requirements: ['Node.js >= 18', 'PostgreSQL >= 14', 'Redis >= 7', 'Docker (optional)'],
    featured: true,
    createdAt: '2024-02-15T09:00:00.000Z',
    updatedAt: '2025-03-10T14:22:00.000Z',
  },
  {
    id: 'prod-02',
    title: 'Payment Gateway Microservice',
    slug: 'payment-gateway-microservice',
    categoryId: 'cat-01',
    shortDescription: 'Stripe-powered payment microservice with subscriptions, invoicing, and webhooks.',
    description: `A complete payment processing microservice integrating Stripe for one-time payments, recurring subscriptions, and usage-based billing. Features webhook handling, automatic retries, invoice generation, refund management, and multi-currency support. Includes battle-tested Node.js/TypeScript source with Docker deployment and Swagger docs.`,
    price: 149,
    currency: 'USD',
    previewImages: [
      { id: 'pi-02-1', productId: 'prod-02', url: '/placeholders/product-02-a.svg', altText: 'Payment flow diagram', sortOrder: 1 },
      { id: 'pi-02-2', productId: 'prod-02', url: '/placeholders/product-02-b.svg', altText: 'Stripe webhook dashboard', sortOrder: 2 },
      { id: 'pi-02-3', productId: 'prod-02', url: '/placeholders/product-02-c.svg', altText: 'Invoice template preview', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/payment-kit',
    tags: [mockTags[0], mockTags[1], mockTags[2], mockTags[12], mockTags[16]],
    technologies: ['Node.js', 'TypeScript', 'Stripe', 'PostgreSQL', 'Docker'],
    version: '1.8.0',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.9,
    reviewCount: 38,
    salesCount: 198,
    downloadLimit: 5,
    requirements: ['Node.js >= 18', 'PostgreSQL >= 14', 'Stripe account'],
    featured: true,
    createdAt: '2024-03-01T09:00:00.000Z',
    updatedAt: '2025-02-18T11:05:00.000Z',
  },
  {
    id: 'prod-03',
    title: 'Notification Service Package',
    slug: 'notification-service-package',
    categoryId: 'cat-01',
    shortDescription: 'Multi-channel notification microservice: email, SMS, push, and in-app alerts.',
    description: `Send notifications across email (SMTP/SendGrid), SMS (Twilio), push (FCM/APNs), and in-app channels from a single microservice. Features templating, scheduling, retry queues, delivery tracking, and user preference management. Built with Node.js, BullMQ, and TypeScript.`,
    price: 89,
    currency: 'USD',
    previewImages: [
      { id: 'pi-03-1', productId: 'prod-03', url: '/placeholders/product-03-a.svg', altText: 'Notification channels overview', sortOrder: 1 },
      { id: 'pi-03-2', productId: 'prod-03', url: '/placeholders/product-03-b.svg', altText: 'Template editor screenshot', sortOrder: 2 },
      { id: 'pi-03-3', productId: 'prod-03', url: '/placeholders/product-03-c.svg', altText: 'Delivery analytics', sortOrder: 3 },
    ],
    tags: [mockTags[0], mockTags[1], mockTags[2], mockTags[15], mockTags[16]],
    technologies: ['Node.js', 'TypeScript', 'BullMQ', 'SendGrid', 'Twilio', 'Redis'],
    version: '1.3.2',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.6,
    reviewCount: 29,
    salesCount: 145,
    downloadLimit: 5,
    requirements: ['Node.js >= 18', 'Redis >= 7', 'SendGrid or SMTP credentials'],
    featured: false,
    createdAt: '2024-04-10T09:00:00.000Z',
    updatedAt: '2025-01-22T08:40:00.000Z',
  },
  {
    id: 'prod-04',
    title: 'SaaS CRM Starter Kit',
    slug: 'saas-crm-starter-kit',
    categoryId: 'cat-02',
    shortDescription: 'Full-stack SaaS CRM with multi-tenancy, billing, and role-based access.',
    description: `Launch your SaaS CRM in days with this complete Next.js + Node.js starter. Includes multi-tenant architecture, Stripe subscription billing, role-based permissions, contact and deal management, activity timeline, email integration, and a polished admin dashboard. Fully typed with TypeScript.`,
    price: 199,
    currency: 'USD',
    previewImages: [
      { id: 'pi-04-1', productId: 'prod-04', url: '/placeholders/product-04-a.svg', altText: 'CRM dashboard overview', sortOrder: 1 },
      { id: 'pi-04-2', productId: 'prod-04', url: '/placeholders/product-04-b.svg', altText: 'Contact management view', sortOrder: 2 },
      { id: 'pi-04-3', productId: 'prod-04', url: '/placeholders/product-04-c.svg', altText: 'Deal pipeline board', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/saas-crm',
    tags: [mockTags[4], mockTags[5], mockTags[6], mockTags[12], mockTags[17]],
    technologies: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Stripe', 'Tailwind CSS'],
    version: '3.1.0',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.7,
    reviewCount: 62,
    salesCount: 289,
    downloadLimit: 3,
    requirements: ['Node.js >= 18', 'PostgreSQL >= 14', 'Stripe account'],
    featured: true,
    createdAt: '2024-01-20T09:00:00.000Z',
    updatedAt: '2025-04-05T16:30:00.000Z',
  },
  {
    id: 'prod-05',
    title: 'Invoice SaaS Dashboard',
    slug: 'invoice-saas-dashboard',
    categoryId: 'cat-02',
    shortDescription: 'Invoicing SaaS with client management, PDF export, and online payments.',
    description: `A feature-complete invoicing application template: create and send professional invoices, track payment status, manage clients, generate PDF reports, and accept online payments via Stripe. Built with Next.js App Router, Prisma ORM, and a beautiful Tailwind UI.`,
    price: 159,
    currency: 'USD',
    previewImages: [
      { id: 'pi-05-1', productId: 'prod-05', url: '/placeholders/product-05-a.svg', altText: 'Invoice list dashboard', sortOrder: 1 },
      { id: 'pi-05-2', productId: 'prod-05', url: '/placeholders/product-05-b.svg', altText: 'Invoice creation form', sortOrder: 2 },
      { id: 'pi-05-3', productId: 'prod-05', url: '/placeholders/product-05-c.svg', altText: 'PDF preview', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/invoice-saas',
    tags: [mockTags[4], mockTags[5], mockTags[6], mockTags[12], mockTags[17]],
    technologies: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Stripe', 'React PDF'],
    version: '2.0.3',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.5,
    reviewCount: 34,
    salesCount: 176,
    downloadLimit: 3,
    requirements: ['Node.js >= 18', 'PostgreSQL >= 14', 'Stripe account'],
    featured: false,
    createdAt: '2024-05-12T09:00:00.000Z',
    updatedAt: '2025-02-28T10:15:00.000Z',
  },
  {
    id: 'prod-06',
    title: 'Analytics SaaS Template',
    slug: 'analytics-saas-template',
    categoryId: 'cat-02',
    shortDescription: 'Analytics platform template with event tracking, funnels, and real-time charts.',
    description: `Build a product analytics SaaS with this comprehensive template. Features event ingestion pipeline, user funnel analysis, retention cohorts, real-time dashboards with Recharts, and a configurable alerting system. Includes a Next.js frontend and a FastAPI data ingestion service.`,
    price: 139,
    currency: 'USD',
    previewImages: [
      { id: 'pi-06-1', productId: 'prod-06', url: '/placeholders/product-06-a.svg', altText: 'Analytics overview chart', sortOrder: 1 },
      { id: 'pi-06-2', productId: 'prod-06', url: '/placeholders/product-06-b.svg', altText: 'Funnel analysis view', sortOrder: 2 },
      { id: 'pi-06-3', productId: 'prod-06', url: '/placeholders/product-06-c.svg', altText: 'Retention cohort table', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/analytics-saas',
    tags: [mockTags[4], mockTags[5], mockTags[14], mockTags[17], mockTags[18]],
    technologies: ['Next.js', 'TypeScript', 'ClickHouse', 'FastAPI', 'Recharts'],
    version: '1.5.0',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.4,
    reviewCount: 21,
    salesCount: 113,
    downloadLimit: 3,
    requirements: ['Node.js >= 18', 'Python >= 3.11', 'ClickHouse or PostgreSQL'],
    featured: false,
    createdAt: '2024-06-08T09:00:00.000Z',
    updatedAt: '2025-03-15T09:00:00.000Z',
  },
  {
    id: 'prod-07',
    title: 'Next.js Landing Page Template',
    slug: 'nextjs-landing-page-template',
    categoryId: 'cat-03',
    shortDescription: 'High-converting SaaS landing page template built with Next.js and Tailwind.',
    description: `A conversion-optimised landing page template for SaaS products. Includes hero, features, pricing, testimonials, FAQ, and CTA sections. Fully responsive, accessible, and shipped with framer-motion animations and a clean component architecture. Dark and light mode included.`,
    price: 79,
    currency: 'USD',
    previewImages: [
      { id: 'pi-07-1', productId: 'prod-07', url: '/placeholders/product-07-a.svg', altText: 'Landing page hero section', sortOrder: 1 },
      { id: 'pi-07-2', productId: 'prod-07', url: '/placeholders/product-07-b.svg', altText: 'Pricing section', sortOrder: 2 },
      { id: 'pi-07-3', productId: 'prod-07', url: '/placeholders/product-07-c.svg', altText: 'Mobile responsive view', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/landing-page',
    tags: [mockTags[4], mockTags[5], mockTags[6]],
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    version: '1.2.0',
    status: 'published',
    licenseType: 'personal',
    rating: 4.6,
    reviewCount: 88,
    salesCount: 521,
    downloadLimit: 3,
    requirements: ['Node.js >= 18'],
    featured: false,
    createdAt: '2024-02-01T09:00:00.000Z',
    updatedAt: '2025-01-10T12:00:00.000Z',
  },
  {
    id: 'prod-08',
    title: 'React Admin Dashboard Template',
    slug: 'react-admin-dashboard-template',
    categoryId: 'cat-04',
    shortDescription: 'Feature-rich React admin dashboard with charts, tables, and role management.',
    description: `A production-grade admin dashboard template with Recharts data visualisation, sortable/filterable data tables, role-based navigation, CRUD form patterns, dark mode, and full TypeScript support. Easily connect to any REST or GraphQL API.`,
    price: 99,
    currency: 'USD',
    previewImages: [
      { id: 'pi-08-1', productId: 'prod-08', url: '/placeholders/product-08-a.svg', altText: 'Admin dashboard main view', sortOrder: 1 },
      { id: 'pi-08-2', productId: 'prod-08', url: '/placeholders/product-08-b.svg', altText: 'Users table with filters', sortOrder: 2 },
      { id: 'pi-08-3', productId: 'prod-08', url: '/placeholders/product-08-c.svg', altText: 'Dark mode variant', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/admin-dashboard',
    tags: [mockTags[4], mockTags[1], mockTags[6], mockTags[18]],
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Recharts', 'TanStack Table'],
    version: '2.3.0',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.7,
    reviewCount: 54,
    salesCount: 367,
    downloadLimit: 3,
    requirements: ['Node.js >= 18'],
    featured: true,
    createdAt: '2024-03-20T09:00:00.000Z',
    updatedAt: '2025-04-01T08:00:00.000Z',
  },
  {
    id: 'prod-09',
    title: 'Figma Mobile App UI Kit',
    slug: 'figma-mobile-app-ui-kit',
    categoryId: 'cat-06',
    shortDescription: '400+ mobile UI components for iOS and Android in a single Figma file.',
    description: `A comprehensive Figma UI kit with 400+ components covering navigation, forms, cards, modals, onboarding, settings, and more. Built with auto-layout, variants, and design tokens. Ships in light and dark variants and is compatible with Figma's Variables feature.`,
    price: 59,
    currency: 'USD',
    previewImages: [
      { id: 'pi-09-1', productId: 'prod-09', url: '/placeholders/product-09-a.svg', altText: 'Component overview page', sortOrder: 1 },
      { id: 'pi-09-2', productId: 'prod-09', url: '/placeholders/product-09-b.svg', altText: 'Form components sheet', sortOrder: 2 },
      { id: 'pi-09-3', productId: 'prod-09', url: '/placeholders/product-09-c.svg', altText: 'Dark mode components', sortOrder: 3 },
    ],
    tags: [mockTags[7]],
    technologies: ['Figma'],
    version: '3.0.0',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.8,
    reviewCount: 112,
    salesCount: 742,
    downloadLimit: 3,
    requirements: ['Figma (free or paid)'],
    featured: true,
    createdAt: '2024-01-15T09:00:00.000Z',
    updatedAt: '2025-02-05T15:00:00.000Z',
  },
  {
    id: 'prod-10',
    title: 'Figma Design System Kit',
    slug: 'figma-design-system-kit',
    categoryId: 'cat-06',
    shortDescription: 'Enterprise-grade Figma design system with tokens, documentation, and web exports.',
    description: `A fully documented Figma design system containing colour tokens, typography scale, spacing system, icon set (500+ icons), and 250+ UI components. Includes a companion Storybook for web and an exported CSS custom properties file. Ideal for product teams building consistent interfaces at scale.`,
    price: 89,
    currency: 'USD',
    previewImages: [
      { id: 'pi-10-1', productId: 'prod-10', url: '/placeholders/product-10-a.svg', altText: 'Token overview page', sortOrder: 1 },
      { id: 'pi-10-2', productId: 'prod-10', url: '/placeholders/product-10-b.svg', altText: 'Component library preview', sortOrder: 2 },
      { id: 'pi-10-3', productId: 'prod-10', url: '/placeholders/product-10-c.svg', altText: 'Icon set sheet', sortOrder: 3 },
    ],
    tags: [mockTags[7]],
    technologies: ['Figma', 'CSS Custom Properties', 'Storybook'],
    version: '2.1.0',
    status: 'published',
    licenseType: 'developer',
    rating: 4.9,
    reviewCount: 76,
    salesCount: 431,
    downloadLimit: 3,
    requirements: ['Figma (paid plan recommended for Variables)'],
    featured: false,
    createdAt: '2024-04-01T09:00:00.000Z',
    updatedAt: '2025-03-20T11:00:00.000Z',
  },
  {
    id: 'prod-11',
    title: 'Photoshop Brand Mockup Pack',
    slug: 'photoshop-brand-mockup-pack',
    categoryId: 'cat-07',
    shortDescription: '60 premium PSD mockups for branding: stationery, packaging, and devices.',
    description: `Present your brand work with 60 high-resolution PSD mockups covering business cards, letterheads, envelopes, packaging, coffee cups, tote bags, and device screens. All smart objects for one-click editing. Compatible with Photoshop CC 2020+.`,
    price: 49,
    currency: 'USD',
    previewImages: [
      { id: 'pi-11-1', productId: 'prod-11', url: '/placeholders/product-11-a.svg', altText: 'Business card mockup', sortOrder: 1 },
      { id: 'pi-11-2', productId: 'prod-11', url: '/placeholders/product-11-b.svg', altText: 'Packaging mockup', sortOrder: 2 },
      { id: 'pi-11-3', productId: 'prod-11', url: '/placeholders/product-11-c.svg', altText: 'Device screen mockup', sortOrder: 3 },
    ],
    tags: [mockTags[8]],
    technologies: ['Photoshop CC 2020+'],
    version: '1.0.0',
    status: 'published',
    licenseType: 'commercial',
    rating: 4.5,
    reviewCount: 93,
    salesCount: 618,
    downloadLimit: 3,
    requirements: ['Adobe Photoshop CC 2020 or newer'],
    featured: false,
    createdAt: '2024-05-05T09:00:00.000Z',
    updatedAt: '2024-12-10T09:00:00.000Z',
  },
  {
    id: 'prod-12',
    title: 'Social Media PSD Template Pack',
    slug: 'social-media-psd-template-pack',
    categoryId: 'cat-07',
    shortDescription: '120 editable PSD templates for Instagram, Facebook, LinkedIn, and Twitter/X.',
    description: `Save hours on social media content with 120 professionally designed PSD templates covering posts, stories, carousel slides, and cover photos for the major platforms. Fully layered and organised for fast editing. Includes 10 colour themes and free fonts list.`,
    price: 39,
    currency: 'USD',
    previewImages: [
      { id: 'pi-12-1', productId: 'prod-12', url: '/placeholders/product-12-a.svg', altText: 'Instagram post templates', sortOrder: 1 },
      { id: 'pi-12-2', productId: 'prod-12', url: '/placeholders/product-12-b.svg', altText: 'Story templates collection', sortOrder: 2 },
      { id: 'pi-12-3', productId: 'prod-12', url: '/placeholders/product-12-c.svg', altText: 'LinkedIn banner templates', sortOrder: 3 },
    ],
    tags: [mockTags[8]],
    technologies: ['Photoshop CC 2018+'],
    version: '1.0.0',
    status: 'published',
    licenseType: 'personal',
    rating: 4.3,
    reviewCount: 141,
    salesCount: 893,
    downloadLimit: 3,
    requirements: ['Adobe Photoshop CC 2018 or newer'],
    featured: false,
    createdAt: '2024-06-01T09:00:00.000Z',
    updatedAt: '2024-11-15T09:00:00.000Z',
  },
  {
    id: 'prod-13',
    title: 'REST API Starter Package',
    slug: 'rest-api-starter-package',
    categoryId: 'cat-09',
    shortDescription: 'Production-ready REST API boilerplate with auth, CRUD, and OpenAPI docs.',
    description: `A carefully crafted REST API starter built with Express and TypeScript. Includes JWT authentication, request validation with Zod, PostgreSQL via Drizzle ORM, Redis caching, rate limiting, automatic OpenAPI/Swagger generation, structured logging, and a complete test suite. Deploy with Docker in minutes.`,
    price: 69,
    currency: 'USD',
    previewImages: [
      { id: 'pi-13-1', productId: 'prod-13', url: '/placeholders/product-13-a.svg', altText: 'Swagger UI preview', sortOrder: 1 },
      { id: 'pi-13-2', productId: 'prod-13', url: '/placeholders/product-13-b.svg', altText: 'Project file structure', sortOrder: 2 },
      { id: 'pi-13-3', productId: 'prod-13', url: '/placeholders/product-13-c.svg', altText: 'Test coverage report', sortOrder: 3 },
    ],
    tags: [mockTags[0], mockTags[1], mockTags[9], mockTags[13], mockTags[14]],
    technologies: ['Node.js', 'TypeScript', 'Express', 'Drizzle ORM', 'PostgreSQL', 'Redis', 'Zod'],
    version: '1.6.0',
    status: 'published',
    licenseType: 'developer',
    rating: 4.7,
    reviewCount: 41,
    salesCount: 224,
    downloadLimit: 5,
    requirements: ['Node.js >= 18', 'PostgreSQL >= 14'],
    featured: false,
    createdAt: '2024-07-10T09:00:00.000Z',
    updatedAt: '2025-04-10T10:30:00.000Z',
  },
  {
    id: 'prod-14',
    title: 'Laravel Module Package',
    slug: 'laravel-module-package',
    categoryId: 'cat-10',
    shortDescription: 'Modular Laravel package skeleton with DDD structure, tests, and CI config.',
    description: `Build maintainable Laravel applications with this domain-driven module skeleton. Includes Service, Repository, and Action layer abstractions, feature tests with Pest, GitHub Actions CI pipeline, and Artisan code generators for modules, commands, and jobs. Compatible with Laravel 10 and 11.`,
    price: 79,
    currency: 'USD',
    previewImages: [
      { id: 'pi-14-1', productId: 'prod-14', url: '/placeholders/product-14-a.svg', altText: 'Module directory structure', sortOrder: 1 },
      { id: 'pi-14-2', productId: 'prod-14', url: '/placeholders/product-14-b.svg', altText: 'Artisan generator output', sortOrder: 2 },
      { id: 'pi-14-3', productId: 'prod-14', url: '/placeholders/product-14-c.svg', altText: 'Test suite screenshot', sortOrder: 3 },
    ],
    tags: [mockTags[10], mockTags[11]],
    technologies: ['PHP 8.2', 'Laravel 10/11', 'Pest', 'GitHub Actions'],
    version: '2.0.0',
    status: 'published',
    licenseType: 'developer',
    rating: 4.6,
    reviewCount: 28,
    salesCount: 159,
    downloadLimit: 5,
    requirements: ['PHP >= 8.2', 'Laravel >= 10', 'Composer'],
    featured: false,
    createdAt: '2024-08-01T09:00:00.000Z',
    updatedAt: '2025-01-30T14:00:00.000Z',
  },
  {
    id: 'prod-15',
    title: 'Developer Documentation Template',
    slug: 'developer-documentation-template',
    categoryId: 'cat-11',
    shortDescription: 'VitePress-based documentation site template with versioning and search.',
    description: `Ship polished developer documentation fast. This VitePress template includes a structured sidebar, versioned docs support, full-text Algolia search integration, dark mode, an interactive API reference component, and a changelog section. Write in MDX, deploy to Vercel or Netlify in one click.`,
    price: 29,
    currency: 'USD',
    previewImages: [
      { id: 'pi-15-1', productId: 'prod-15', url: '/placeholders/product-15-a.svg', altText: 'Documentation home page', sortOrder: 1 },
      { id: 'pi-15-2', productId: 'prod-15', url: '/placeholders/product-15-b.svg', altText: 'API reference page', sortOrder: 2 },
      { id: 'pi-15-3', productId: 'prod-15', url: '/placeholders/product-15-c.svg', altText: 'Dark mode docs view', sortOrder: 3 },
    ],
    demoUrl: 'https://demo.digital-market.dev/docs-template',
    tags: [mockTags[5], mockTags[19]],
    technologies: ['VitePress', 'MDX', 'Algolia DocSearch'],
    version: '1.1.0',
    status: 'published',
    licenseType: 'personal',
    rating: 4.4,
    reviewCount: 66,
    salesCount: 478,
    downloadLimit: 3,
    requirements: ['Node.js >= 18'],
    featured: false,
    createdAt: '2024-09-15T09:00:00.000Z',
    updatedAt: '2025-03-01T12:00:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Admin Users
// ─────────────────────────────────────────────

export const mockAdminUsers: User[] = [
  {
    id: 'admin-01',
    email: 'owner@digital-market.dev',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    displayName: 'Sarah Mitchell',
    role: 'super_admin',
    status: 'active',
    emailVerified: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-04-20T08:00:00.000Z',
    lastLoginAt: '2025-05-15T09:12:00.000Z',
  },
  {
    id: 'admin-02',
    email: 'james@digital-market.dev',
    firstName: 'James',
    lastName: 'Torres',
    displayName: 'James Torres',
    role: 'admin',
    status: 'active',
    emailVerified: true,
    createdAt: '2024-02-01T00:00:00.000Z',
    updatedAt: '2025-03-15T10:00:00.000Z',
    lastLoginAt: '2025-05-14T11:45:00.000Z',
  },
  {
    id: 'admin-03',
    email: 'support@digital-market.dev',
    firstName: 'Priya',
    lastName: 'Nair',
    displayName: 'Priya Nair',
    role: 'support',
    status: 'active',
    emailVerified: true,
    createdAt: '2024-03-01T00:00:00.000Z',
    updatedAt: '2025-02-28T14:00:00.000Z',
    lastLoginAt: '2025-05-16T07:30:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Customers
// ─────────────────────────────────────────────

export const mockCustomers: User[] = [
  {
    id: 'user-01',
    email: 'alex.johnson@example.com',
    firstName: 'Alex',
    lastName: 'Johnson',
    displayName: 'Alex Johnson',
    role: 'customer',
    status: 'active',
    emailVerified: true,
    billingAddress: {
      line1: '142 Maple Street',
      city: 'Austin',
      state: 'TX',
      postalCode: '78701',
      country: 'US',
    },
    createdAt: '2024-03-10T14:22:00.000Z',
    updatedAt: '2025-04-18T10:30:00.000Z',
    lastLoginAt: '2025-05-15T19:40:00.000Z',
  },
  {
    id: 'user-02',
    email: 'maria.santos@example.com',
    firstName: 'Maria',
    lastName: 'Santos',
    displayName: 'Maria Santos',
    role: 'customer',
    status: 'active',
    emailVerified: true,
    billingAddress: {
      line1: '87 Ocean Drive',
      city: 'Miami',
      state: 'FL',
      postalCode: '33101',
      country: 'US',
    },
    createdAt: '2024-04-05T08:10:00.000Z',
    updatedAt: '2025-03-22T09:00:00.000Z',
    lastLoginAt: '2025-05-14T12:15:00.000Z',
  },
  {
    id: 'user-03',
    email: 'liam.chen@example.com',
    firstName: 'Liam',
    lastName: 'Chen',
    displayName: 'Liam Chen',
    role: 'customer',
    status: 'active',
    emailVerified: true,
    billingAddress: {
      line1: '300 Market Street',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94103',
      country: 'US',
    },
    createdAt: '2024-05-18T11:00:00.000Z',
    updatedAt: '2025-04-01T16:00:00.000Z',
    lastLoginAt: '2025-05-16T08:00:00.000Z',
  },
  {
    id: 'user-04',
    email: 'aisha.rahman@example.com',
    firstName: 'Aisha',
    lastName: 'Rahman',
    displayName: 'Aisha Rahman',
    role: 'customer',
    status: 'active',
    emailVerified: true,
    billingAddress: {
      line1: '22 Baker Street',
      city: 'London',
      postalCode: 'NW1 6XE',
      country: 'GB',
    },
    createdAt: '2024-06-22T09:30:00.000Z',
    updatedAt: '2025-02-10T14:00:00.000Z',
    lastLoginAt: '2025-05-13T20:05:00.000Z',
  },
  {
    id: 'user-05',
    email: 'carlos.mendez@example.com',
    firstName: 'Carlos',
    lastName: 'Mendez',
    displayName: 'Carlos Mendez',
    role: 'customer',
    status: 'active',
    emailVerified: true,
    billingAddress: {
      line1: 'Calle Gran Vía 40',
      city: 'Madrid',
      postalCode: '28013',
      country: 'ES',
    },
    createdAt: '2024-07-14T16:45:00.000Z',
    updatedAt: '2025-01-28T11:00:00.000Z',
    lastLoginAt: '2025-05-10T15:30:00.000Z',
  },
  {
    id: 'user-06',
    email: 'yuki.tanaka@example.com',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    displayName: 'Yuki Tanaka',
    role: 'customer',
    status: 'active',
    emailVerified: true,
    billingAddress: {
      line1: '1-2-3 Shibuya',
      city: 'Tokyo',
      postalCode: '150-0002',
      country: 'JP',
    },
    createdAt: '2024-08-30T07:00:00.000Z',
    updatedAt: '2025-03-05T08:00:00.000Z',
    lastLoginAt: '2025-05-12T06:20:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Orders
// ─────────────────────────────────────────────

const makeOrderItem = (
  id: string,
  orderId: string,
  product: Product,
  licenseType: OrderItem['licenseType'] = 'commercial',
): OrderItem => ({
  id,
  orderId,
  productId: product.id,
  product,
  quantity: 1,
  unitPrice: product.salePrice ?? product.price,
  licenseType,
});

export const mockOrders: Order[] = [
  {
    id: 'order-01',
    userId: 'user-01',
    user: mockCustomers[0],
    items: [makeOrderItem('oi-01-1', 'order-01', mockProducts[0])],
    subtotal: 129,
    discountAmount: 0,
    total: 129,
    currency: 'USD',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_001',
    invoiceId: 'inv-01',
    createdAt: '2025-01-08T10:22:00.000Z',
    updatedAt: '2025-01-08T10:23:00.000Z',
  },
  {
    id: 'order-02',
    userId: 'user-02',
    user: mockCustomers[1],
    items: [makeOrderItem('oi-02-1', 'order-02', mockProducts[3])],
    subtotal: 199,
    discountAmount: 39.8,
    total: 159.2,
    currency: 'USD',
    couponCode: 'SAVE20',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_002',
    invoiceId: 'inv-02',
    createdAt: '2025-01-15T14:05:00.000Z',
    updatedAt: '2025-01-15T14:06:00.000Z',
  },
  {
    id: 'order-03',
    userId: 'user-03',
    user: mockCustomers[2],
    items: [
      makeOrderItem('oi-03-1', 'order-03', mockProducts[6]),
      makeOrderItem('oi-03-2', 'order-03', mockProducts[14]),
    ],
    subtotal: 108,
    discountAmount: 54,
    total: 54,
    currency: 'USD',
    couponCode: 'LAUNCH50',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_003',
    invoiceId: 'inv-03',
    createdAt: '2025-01-22T09:15:00.000Z',
    updatedAt: '2025-01-22T09:16:00.000Z',
  },
  {
    id: 'order-04',
    userId: 'user-04',
    user: mockCustomers[3],
    items: [makeOrderItem('oi-04-1', 'order-04', mockProducts[8])],
    subtotal: 59,
    discountAmount: 0,
    total: 59,
    currency: 'USD',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'paypal',
    paymentIntentId: 'pi_mock_004',
    invoiceId: 'inv-04',
    createdAt: '2025-02-03T16:40:00.000Z',
    updatedAt: '2025-02-03T16:41:00.000Z',
  },
  {
    id: 'order-05',
    userId: 'user-05',
    user: mockCustomers[4],
    items: [makeOrderItem('oi-05-1', 'order-05', mockProducts[1])],
    subtotal: 149,
    discountAmount: 0,
    total: 149,
    currency: 'USD',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_005',
    invoiceId: 'inv-05',
    createdAt: '2025-02-10T11:00:00.000Z',
    updatedAt: '2025-02-10T11:01:00.000Z',
  },
  {
    id: 'order-06',
    userId: 'user-06',
    user: mockCustomers[5],
    items: [makeOrderItem('oi-06-1', 'order-06', mockProducts[9])],
    subtotal: 89,
    discountAmount: 8.9,
    total: 80.1,
    currency: 'USD',
    couponCode: 'WELCOME10',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_006',
    invoiceId: 'inv-06',
    createdAt: '2025-02-18T08:30:00.000Z',
    updatedAt: '2025-02-18T08:31:00.000Z',
  },
  {
    id: 'order-07',
    userId: 'user-01',
    user: mockCustomers[0],
    items: [makeOrderItem('oi-07-1', 'order-07', mockProducts[7])],
    subtotal: 99,
    discountAmount: 0,
    total: 99,
    currency: 'USD',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_007',
    invoiceId: 'inv-07',
    createdAt: '2025-03-05T13:22:00.000Z',
    updatedAt: '2025-03-05T13:23:00.000Z',
  },
  {
    id: 'order-08',
    userId: 'user-02',
    user: mockCustomers[1],
    items: [makeOrderItem('oi-08-1', 'order-08', mockProducts[12])],
    subtotal: 69,
    discountAmount: 0,
    total: 69,
    currency: 'USD',
    orderStatus: 'refunded',
    paymentStatus: 'refunded',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_008',
    invoiceId: 'inv-08',
    notes: 'Refunded upon customer request — compatibility issue.',
    createdAt: '2025-03-12T17:10:00.000Z',
    updatedAt: '2025-03-14T09:00:00.000Z',
  },
  {
    id: 'order-09',
    userId: 'user-03',
    user: mockCustomers[2],
    items: [makeOrderItem('oi-09-1', 'order-09', mockProducts[4])],
    subtotal: 159,
    discountAmount: 0,
    total: 159,
    currency: 'USD',
    orderStatus: 'pending',
    paymentStatus: 'pending',
    paymentMethod: 'card',
    createdAt: '2025-05-16T07:55:00.000Z',
    updatedAt: '2025-05-16T07:55:00.000Z',
  },
  {
    id: 'order-10',
    userId: 'user-04',
    user: mockCustomers[3],
    items: [
      makeOrderItem('oi-10-1', 'order-10', mockProducts[2]),
      makeOrderItem('oi-10-2', 'order-10', mockProducts[13]),
    ],
    subtotal: 168,
    discountAmount: 0,
    total: 168,
    currency: 'USD',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_010',
    invoiceId: 'inv-10',
    createdAt: '2025-04-22T15:00:00.000Z',
    updatedAt: '2025-04-22T15:01:00.000Z',
  },
  {
    id: 'order-11',
    userId: 'user-05',
    user: mockCustomers[4],
    items: [makeOrderItem('oi-11-1', 'order-11', mockProducts[10])],
    subtotal: 49,
    discountAmount: 0,
    total: 49,
    currency: 'USD',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'paypal',
    paymentIntentId: 'pi_mock_011',
    invoiceId: 'inv-11',
    createdAt: '2025-04-28T12:30:00.000Z',
    updatedAt: '2025-04-28T12:31:00.000Z',
  },
  {
    id: 'order-12',
    userId: 'user-06',
    user: mockCustomers[5],
    items: [makeOrderItem('oi-12-1', 'order-12', mockProducts[5])],
    subtotal: 139,
    discountAmount: 13.9,
    total: 125.1,
    currency: 'USD',
    couponCode: 'WELCOME10',
    orderStatus: 'paid',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    paymentIntentId: 'pi_mock_012',
    invoiceId: 'inv-12',
    createdAt: '2025-05-02T10:10:00.000Z',
    updatedAt: '2025-05-02T10:11:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Coupons
// ─────────────────────────────────────────────

export const mockCoupons: Coupon[] = [
  {
    id: 'coupon-01',
    code: 'SAVE20',
    type: 'percentage',
    value: 20,
    minOrderAmount: 50,
    usageLimit: 500,
    usageCount: 187,
    perUserLimit: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  },
  {
    id: 'coupon-02',
    code: 'LAUNCH50',
    type: 'percentage',
    value: 50,
    minOrderAmount: 80,
    maxDiscountAmount: 75,
    usageLimit: 100,
    usageCount: 100,
    perUserLimit: 1,
    expiresAt: '2025-02-28T23:59:59.000Z',
    isActive: false,
    createdAt: '2025-01-10T00:00:00.000Z',
    updatedAt: '2025-03-01T00:00:00.000Z',
  },
  {
    id: 'coupon-03',
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    usageLimit: undefined,
    usageCount: 312,
    perUserLimit: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-05-10T00:00:00.000Z',
  },
  {
    id: 'coupon-04',
    code: 'FLAT15',
    type: 'fixed',
    value: 15,
    minOrderAmount: 60,
    usageLimit: 200,
    usageCount: 43,
    isActive: true,
    createdAt: '2025-03-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Support Tickets
// ─────────────────────────────────────────────

const mockReply = (
  id: string,
  ticketId: string,
  authorId: string,
  message: string,
  isStaff: boolean,
  createdAt: string,
): SupportReply => ({
  id,
  ticketId,
  authorId,
  message,
  isStaff,
  createdAt,
  updatedAt: createdAt,
});

export const mockTickets: SupportTicket[] = [
  {
    id: 'ticket-01',
    userId: 'user-01',
    user: mockCustomers[0],
    subject: 'Docker compose fails on M2 Mac',
    message: 'When I run docker-compose up on my M2 MacBook the auth service exits with code 1. I\'ve attached the logs.',
    status: 'resolved',
    priority: 'high',
    productId: 'prod-01',
    orderId: 'order-01',
    replies: [
      mockReply('reply-01-1', 'ticket-01', 'admin-03', 'Hi Alex, thanks for the report. This is a known ARM64 issue in v2.4.0. Please update to v2.4.1 using `docker pull` — the fix is included.', true, '2025-01-09T08:30:00.000Z'),
      mockReply('reply-01-2', 'ticket-01', 'user-01', 'That fixed it, thank you!', false, '2025-01-09T10:00:00.000Z'),
    ],
    assignedToId: 'admin-03',
    resolvedAt: '2025-01-09T10:05:00.000Z',
    createdAt: '2025-01-08T18:00:00.000Z',
    updatedAt: '2025-01-09T10:05:00.000Z',
  },
  {
    id: 'ticket-02',
    userId: 'user-02',
    user: mockCustomers[1],
    subject: 'Stripe webhook signature validation failing',
    message: 'I\'ve set STRIPE_WEBHOOK_SECRET in my .env but every webhook returns 400. I\'m using the Stripe CLI for local testing.',
    status: 'resolved',
    priority: 'high',
    productId: 'prod-02',
    orderId: 'order-05',
    replies: [
      mockReply('reply-02-1', 'ticket-02', 'admin-03', 'Hi Maria, when using Stripe CLI the webhook secret is different from the dashboard one. Use `stripe listen --print-secret` to get the correct local secret.', true, '2025-02-11T09:00:00.000Z'),
      mockReply('reply-02-2', 'ticket-02', 'user-02', 'Perfect, that was it! Works now.', false, '2025-02-11T11:30:00.000Z'),
    ],
    assignedToId: 'admin-03',
    resolvedAt: '2025-02-11T11:35:00.000Z',
    createdAt: '2025-02-10T20:00:00.000Z',
    updatedAt: '2025-02-11T11:35:00.000Z',
  },
  {
    id: 'ticket-03',
    userId: 'user-03',
    user: mockCustomers[2],
    subject: 'How to add a custom pricing tier to Invoice SaaS?',
    message: 'I need to add a "Team" tier at $79/month on top of the existing Free and Pro tiers. Where should I start?',
    status: 'open',
    priority: 'medium',
    productId: 'prod-05',
    orderId: 'order-03',
    replies: [
      mockReply('reply-03-1', 'ticket-03', 'admin-03', 'Hi Liam! You can add a new tier in `src/config/pricing.ts`. Check the CUSTOMISATION section of the docs for a step-by-step guide. Happy to help further if you get stuck.', true, '2025-01-23T10:00:00.000Z'),
    ],
    assignedToId: 'admin-03',
    createdAt: '2025-01-22T20:00:00.000Z',
    updatedAt: '2025-01-23T10:00:00.000Z',
  },
  {
    id: 'ticket-04',
    userId: 'user-04',
    user: mockCustomers[3],
    subject: 'Request refund — Figma file corrupted',
    message: 'The downloaded Figma file throws "Cannot open file" error. I\'ve tried re-downloading three times.',
    status: 'resolved',
    priority: 'urgent',
    productId: 'prod-09',
    orderId: 'order-04',
    replies: [
      mockReply('reply-04-1', 'ticket-04', 'admin-02', 'Hi Aisha, so sorry for the trouble. We\'ve fixed the corrupted file — please download again from your downloads page. We\'ve also credited your account with a 10% coupon as an apology.', true, '2025-02-04T09:00:00.000Z'),
      mockReply('reply-04-2', 'ticket-04', 'user-04', 'It works now! Thank you for the quick response and the coupon.', false, '2025-02-04T12:00:00.000Z'),
    ],
    assignedToId: 'admin-02',
    resolvedAt: '2025-02-04T12:05:00.000Z',
    createdAt: '2025-02-03T22:00:00.000Z',
    updatedAt: '2025-02-04T12:05:00.000Z',
  },
  {
    id: 'ticket-05',
    userId: 'user-05',
    user: mockCustomers[4],
    subject: 'Payment microservice not sending email receipts',
    message: 'After a successful charge the customer doesn\'t receive an email receipt even though MAILER_HOST is configured. Am I missing a step?',
    status: 'in_progress',
    priority: 'medium',
    productId: 'prod-02',
    orderId: 'order-05',
    replies: [
      mockReply('reply-05-1', 'ticket-05', 'admin-03', 'Hi Carlos, can you confirm which version you\'re running and share the relevant section of your .env (redact credentials)? I\'ll look into it right away.', true, '2025-02-11T10:00:00.000Z'),
    ],
    assignedToId: 'admin-03',
    createdAt: '2025-02-10T18:00:00.000Z',
    updatedAt: '2025-02-11T10:00:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Reviews
// ─────────────────────────────────────────────

export const mockReviews: Review[] = [
  { id: 'rev-01', productId: 'prod-01', userId: 'user-01', orderId: 'order-01', rating: 5, title: 'Saved us weeks of work', body: 'We used this to bootstrap our auth layer and it handled every edge case we threw at it. Docs are excellent.', status: 'approved', helpfulCount: 24, verifiedPurchase: true, createdAt: '2025-01-20T12:00:00.000Z', updatedAt: '2025-01-20T12:00:00.000Z' },
  { id: 'rev-02', productId: 'prod-01', userId: 'user-03', orderId: 'order-03', rating: 5, title: 'Production-ready out of the box', body: 'Deployed to Kubernetes in under an hour. The Helm chart was a nice bonus. Highly recommend.', status: 'approved', helpfulCount: 18, verifiedPurchase: true, createdAt: '2025-02-01T09:00:00.000Z', updatedAt: '2025-02-01T09:00:00.000Z' },
  { id: 'rev-03', productId: 'prod-02', userId: 'user-02', orderId: 'order-02', rating: 5, title: 'Best Stripe integration I\'ve seen', body: 'The webhook handling and retry logic alone are worth the price. Subscription management is seamless.', status: 'approved', helpfulCount: 31, verifiedPurchase: true, createdAt: '2025-01-25T14:00:00.000Z', updatedAt: '2025-01-25T14:00:00.000Z' },
  { id: 'rev-04', productId: 'prod-02', userId: 'user-05', orderId: 'order-05', rating: 4, title: 'Great package, minor email quirk', body: 'Everything works great but the receipt emails need extra config that isn\'t well documented. Support was helpful though.', status: 'approved', helpfulCount: 9, verifiedPurchase: true, createdAt: '2025-02-20T16:00:00.000Z', updatedAt: '2025-02-20T16:00:00.000Z' },
  { id: 'rev-05', productId: 'prod-04', userId: 'user-02', orderId: 'order-02', rating: 5, title: 'Shipped our MVP in 2 weeks', body: 'The multi-tenancy setup and Stripe billing integration are solid. Saved us months of boilerplate. Worth every cent.', status: 'approved', helpfulCount: 42, verifiedPurchase: true, createdAt: '2025-01-30T10:00:00.000Z', updatedAt: '2025-01-30T10:00:00.000Z' },
  { id: 'rev-06', productId: 'prod-04', userId: 'user-06', orderId: 'order-06', rating: 4, title: 'Solid foundation', body: 'Well structured and easy to extend. I wish the tests were more comprehensive out of the box.', status: 'approved', helpfulCount: 7, verifiedPurchase: true, createdAt: '2025-03-10T11:00:00.000Z', updatedAt: '2025-03-10T11:00:00.000Z' },
  { id: 'rev-07', productId: 'prod-07', userId: 'user-03', orderId: 'order-03', rating: 5, title: 'Stunning design, great code', body: 'My client loved the design and the code is clean and well commented. Dark mode works perfectly.', status: 'approved', helpfulCount: 55, verifiedPurchase: true, createdAt: '2025-02-05T08:00:00.000Z', updatedAt: '2025-02-05T08:00:00.000Z' },
  { id: 'rev-08', productId: 'prod-08', userId: 'user-01', orderId: 'order-07', rating: 5, title: 'Best admin template I\'ve tried', body: 'The table implementation with TanStack is perfect. Sorting, filtering, and pagination all work flawlessly.', status: 'approved', helpfulCount: 27, verifiedPurchase: true, createdAt: '2025-03-15T14:00:00.000Z', updatedAt: '2025-03-15T14:00:00.000Z' },
  { id: 'rev-09', productId: 'prod-09', userId: 'user-04', orderId: 'order-04', rating: 5, title: 'Worth every penny', body: 'The auto-layout is meticulous and the dark mode variants are beautifully crafted. Saved me at least 40 hours.', status: 'approved', helpfulCount: 63, verifiedPurchase: true, createdAt: '2025-02-12T09:00:00.000Z', updatedAt: '2025-02-12T09:00:00.000Z' },
  { id: 'rev-10', productId: 'prod-09', userId: 'user-06', orderId: 'order-06', rating: 4, title: 'Very comprehensive', body: 'Massive component library with great coverage. Took me a while to navigate but the organisation makes sense once you get it.', status: 'approved', helpfulCount: 19, verifiedPurchase: true, createdAt: '2025-02-25T10:00:00.000Z', updatedAt: '2025-02-25T10:00:00.000Z' },
  { id: 'rev-11', productId: 'prod-10', userId: 'user-06', orderId: 'order-06', rating: 5, title: 'Enterprise-grade quality', body: 'The token system is thoughtfully designed and the Storybook companion makes handoff to developers a breeze.', status: 'approved', helpfulCount: 38, verifiedPurchase: true, createdAt: '2025-03-05T11:00:00.000Z', updatedAt: '2025-03-05T11:00:00.000Z' },
  { id: 'rev-12', productId: 'prod-11', userId: 'user-05', orderId: 'order-11', rating: 4, title: 'Great mockups', body: 'High quality PSDs, smart objects work perfectly. The packaging mockups especially are stunning.', status: 'approved', helpfulCount: 14, verifiedPurchase: true, createdAt: '2025-05-02T09:00:00.000Z', updatedAt: '2025-05-02T09:00:00.000Z' },
  { id: 'rev-13', productId: 'prod-13', userId: 'user-03', orderId: 'order-03', rating: 5, title: 'Best API boilerplate I\'ve used', body: 'Drizzle ORM integration is clean, Zod validation catches everything, and the OpenAPI generation saves so much time.', status: 'approved', helpfulCount: 22, verifiedPurchase: true, createdAt: '2025-02-08T13:00:00.000Z', updatedAt: '2025-02-08T13:00:00.000Z' },
  { id: 'rev-14', productId: 'prod-14', userId: 'user-04', orderId: 'order-10', rating: 5, title: 'Exactly what I needed', body: 'The DDD structure is opinionated in all the right ways and the Artisan generators speed things up massively.', status: 'approved', helpfulCount: 16, verifiedPurchase: true, createdAt: '2025-05-01T10:00:00.000Z', updatedAt: '2025-05-01T10:00:00.000Z' },
  { id: 'rev-15', productId: 'prod-15', userId: 'user-03', orderId: 'order-03', rating: 4, title: 'Clean and easy to customise', body: 'Set up Algolia in 30 minutes and the versioned docs worked perfectly. Would be 5 stars with more example content.', status: 'approved', helpfulCount: 11, verifiedPurchase: true, createdAt: '2025-02-18T15:00:00.000Z', updatedAt: '2025-02-18T15:00:00.000Z' },
  { id: 'rev-16', productId: 'prod-03', userId: 'user-04', orderId: 'order-10', rating: 4, title: 'Solid notification service', body: 'FCM push and email templating work great. SMS via Twilio took some extra config but the docs helped.', status: 'approved', helpfulCount: 8, verifiedPurchase: true, createdAt: '2025-05-05T09:00:00.000Z', updatedAt: '2025-05-05T09:00:00.000Z' },
];

// ─────────────────────────────────────────────
// Downloads
// ─────────────────────────────────────────────

export const mockDownloads: Download[] = [
  { id: 'dl-01', userId: 'user-01', orderId: 'order-01', productId: 'prod-01', fileId: 'file-prod-01', downloadCount: 2, downloadLimit: 5, createdAt: '2025-01-08T10:25:00.000Z' },
  { id: 'dl-02', userId: 'user-02', orderId: 'order-02', productId: 'prod-04', fileId: 'file-prod-04', downloadCount: 1, downloadLimit: 3, createdAt: '2025-01-15T14:10:00.000Z' },
  { id: 'dl-03', userId: 'user-03', orderId: 'order-03', productId: 'prod-07', fileId: 'file-prod-07', downloadCount: 3, downloadLimit: 3, createdAt: '2025-01-22T09:20:00.000Z' },
  { id: 'dl-04', userId: 'user-03', orderId: 'order-03', productId: 'prod-15', fileId: 'file-prod-15', downloadCount: 1, downloadLimit: 3, createdAt: '2025-01-22T09:21:00.000Z' },
  { id: 'dl-05', userId: 'user-04', orderId: 'order-04', productId: 'prod-09', fileId: 'file-prod-09', downloadCount: 1, downloadLimit: 3, createdAt: '2025-02-03T16:45:00.000Z' },
  { id: 'dl-06', userId: 'user-05', orderId: 'order-05', productId: 'prod-02', fileId: 'file-prod-02', downloadCount: 2, downloadLimit: 5, createdAt: '2025-02-10T11:05:00.000Z' },
];

// ─────────────────────────────────────────────
// Cart (current session)
// ─────────────────────────────────────────────

export const mockCart: Cart = {
  id: 'cart-session-01',
  sessionId: 'sess-abc123',
  items: [],
  subtotal: 0,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// ─────────────────────────────────────────────
// Static Pages
// ─────────────────────────────────────────────

export const mockStaticPages: StaticPage[] = [
  {
    id: 'page-01',
    title: 'About Us',
    slug: 'about',
    content: '<h1>About Digital Market</h1><p>We are a marketplace for premium digital products built by developers, for developers.</p>',
    metaTitle: 'About Digital Market — Premium Dev Tools',
    metaDescription: 'Learn about Digital Market, the marketplace for premium developer resources and templates.',
    isPublished: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-01-10T00:00:00.000Z',
  },
  {
    id: 'page-02',
    title: 'Terms of Service',
    slug: 'terms',
    content: '<h1>Terms of Service</h1><p>By purchasing from Digital Market, you agree to the following terms...</p>',
    metaTitle: 'Terms of Service — Digital Market',
    isPublished: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-06-01T00:00:00.000Z',
  },
  {
    id: 'page-03',
    title: 'Privacy Policy',
    slug: 'privacy',
    content: '<h1>Privacy Policy</h1><p>We respect your privacy and are committed to protecting your personal data...</p>',
    metaTitle: 'Privacy Policy — Digital Market',
    isPublished: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-06-01T00:00:00.000Z',
  },
  {
    id: 'page-04',
    title: 'Refund Policy',
    slug: 'refund-policy',
    content: '<h1>Refund Policy</h1><p>We offer a 14-day no-questions-asked refund on all products...</p>',
    metaTitle: 'Refund Policy — Digital Market',
    isPublished: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-08-15T00:00:00.000Z',
  },
];

// ─────────────────────────────────────────────
// FAQs
// ─────────────────────────────────────────────

export const mockFAQs: FAQ[] = [
  { id: 'faq-01', question: 'What license do I get with my purchase?', answer: 'Each product page clearly states the license type (Personal, Commercial, Extended, or Developer). Commercial licenses allow use in client projects; Developer licenses allow use in SaaS products you sell.', sortOrder: 1, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
  { id: 'faq-02', question: 'How many times can I download a product?', answer: 'Each purchase includes a set number of downloads shown on the product page (typically 3–5). Contact support if you need additional downloads.', sortOrder: 2, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
  { id: 'faq-03', question: 'Do I get free updates after purchasing?', answer: 'Yes. All updates within the same major version are free. You\'ll see new versions appear in your downloads dashboard automatically.', sortOrder: 3, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
  { id: 'faq-04', question: 'What payment methods do you accept?', answer: 'We accept all major credit/debit cards (Visa, Mastercard, Amex) and PayPal. All payments are processed securely via Stripe.', sortOrder: 4, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
  { id: 'faq-05', question: 'Can I use a product in multiple projects?', answer: 'This depends on your license type. Personal licenses cover one project. Commercial licenses cover unlimited client projects. Developer licenses cover products you build and sell.', sortOrder: 5, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
  { id: 'faq-06', question: 'What is your refund policy?', answer: 'We offer a 14-day refund policy. If you\'re not satisfied, contact support within 14 days of purchase and we\'ll process a full refund.', sortOrder: 6, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
  { id: 'faq-07', question: 'Do you offer team or agency licensing?', answer: 'Yes. Our Developer licenses are designed for teams and agencies. Contact us if you need custom multi-seat licensing.', sortOrder: 7, isPublished: true, createdAt: '2024-01-01T00:00:00.000Z', updatedAt: '2024-01-01T00:00:00.000Z' },
];

// ─────────────────────────────────────────────
// Blog Posts
// ─────────────────────────────────────────────

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'blog-01',
    title: 'Building Scalable Microservices with Node.js and TypeScript',
    slug: 'building-scalable-microservices-nodejs-typescript',
    excerpt: 'A deep dive into structuring production-ready microservices with TypeScript, covering inter-service communication, error handling, and deployment.',
    content: '<h2>Introduction</h2><p>Microservices architecture enables teams to deploy and scale independently...</p>',
    authorId: 'admin-01',
    tags: [mockTags[0], mockTags[1], mockTags[16]],
    status: 'published',
    publishedAt: '2025-03-15T09:00:00.000Z',
    readingTimeMinutes: 12,
    createdAt: '2025-03-10T09:00:00.000Z',
    updatedAt: '2025-03-15T09:00:00.000Z',
  },
  {
    id: 'blog-02',
    title: 'The SaaS Tech Stack in 2025: What We Chose and Why',
    slug: 'saas-tech-stack-2025',
    excerpt: 'We evaluated dozens of tools before settling on our current stack. Here\'s the reasoning behind every major choice.',
    content: '<h2>Why Stack Decisions Matter</h2><p>The wrong stack choice can haunt a team for years...</p>',
    authorId: 'admin-02',
    tags: [mockTags[5], mockTags[17], mockTags[6]],
    status: 'published',
    publishedAt: '2025-04-01T09:00:00.000Z',
    readingTimeMinutes: 8,
    createdAt: '2025-03-28T09:00:00.000Z',
    updatedAt: '2025-04-01T09:00:00.000Z',
  },
];

// ─────────────────────────────────────────────
// Dashboard Stats
// ─────────────────────────────────────────────

export const mockDashboardStats: DashboardStats = {
  totalRevenue: 48320,
  totalOrders: 312,
  totalCustomers: 1840,
  totalProducts: 15,
  revenueGrowthPercent: 18.4,
  ordersGrowthPercent: 12.1,
  customersGrowthPercent: 9.7,
  recentOrders: mockOrders.slice(-5).reverse(),
  topProducts: [
    { productId: 'prod-09', title: 'Figma Mobile App UI Kit', slug: 'figma-mobile-app-ui-kit', salesCount: 742, revenue: 43778, thumbnailUrl: '/placeholders/product-09-a.svg' },
    { productId: 'prod-12', title: 'Social Media PSD Template Pack', slug: 'social-media-psd-template-pack', salesCount: 893, revenue: 34827, thumbnailUrl: '/placeholders/product-12-a.svg' },
    { productId: 'prod-07', title: 'Next.js Landing Page Template', slug: 'nextjs-landing-page-template', salesCount: 521, revenue: 41159, thumbnailUrl: '/placeholders/product-07-a.svg' },
  ],
  salesChart: [
    { month: 'Jun 2024', revenue: 1820, orders: 14 },
    { month: 'Jul 2024', revenue: 2640, orders: 19 },
    { month: 'Aug 2024', revenue: 3180, orders: 23 },
    { month: 'Sep 2024', revenue: 2950, orders: 20 },
    { month: 'Oct 2024', revenue: 4120, orders: 28 },
    { month: 'Nov 2024', revenue: 5380, orders: 36 },
    { month: 'Dec 2024', revenue: 6720, orders: 45 },
    { month: 'Jan 2025', revenue: 4980, orders: 33 },
    { month: 'Feb 2025', revenue: 5340, orders: 37 },
    { month: 'Mar 2025', revenue: 5890, orders: 39 },
    { month: 'Apr 2025', revenue: 3250, orders: 23 },
    { month: 'May 2025', revenue: 2050, orders: 15 },
  ],
};
